
- hosts: 103.189.234.152
  gather_facts: yes
  become: yes
  become_user: root
  vars:
    pub: /root/.ssh/id_rsa.pub
    config: /root/.ssh/config
    destination: /home/ega/.ssh/authorized_keys
    release: focal
  tasks:
    - name: "Update and upgrade systems"
      apt:
        update_cache: yes
        upgrade: dist
    - name: "Install dependencies"
      apt:
        name:
          - apt-transport-https
          - gnupg-agent
          - zip
          - unzip
          - build-essential
          - ncdu
    - name: "Add gpg docker to servers"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: "Add docker repository to servers"
      apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release }} stable
      state: present
    - name: "Install docker"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - python3-pip
    - name: "Start systemd docker"
      systemd:
        state: started
        name: docker
        enabled: yes
    - name: "create alias for docker-compose"
      lineinfile:
        path: /home/ega/.bashrc
        insertafter: EOF
        line: "alias docker-compose='docker compose'"
    - name: "Creates file ssh config"
      file:
        path: .ssh/authorized_keys
        state: touch
    - name: "copy pub.key"
      copy:
        src: /root/.ssh/id_rsa.pub
        dest: /home/ega/.ssh
    - name: "add authorized.keys"
      copy:
        src: /root/.ssh/id_rsa.pub
        dest: /home/ega/.ssh/authorized_keys